// export const GET_EMPLOYEE_URL = '/api/employee/getEmployee.action'
export const GET_EMPLOYEE_URL = '/api/employee/getEmployee'
export const CREATE_EMPLOYEE_URL = '/api/employee/createEmployee'
export const UPDATE_EMPLOYEE_URL = '/api/employee/updateEmployee'
export const DELETE_EMPLOYEE_URL = '/api/employee/deleteEmployee'
export const DOWNLOAD_EMPLOYEE_URL = '/api/employee/downloadEmployee'
